### ISSUE TITLE
create flist server

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/rfs#61]
Create a server to expose docker images conversion API

Related issue: https://github.com/threefoldtech/home/issues/1497

**Comment by rawdaGastan** [comment]
### Tasks

- [ ] add endpoint to create flist and return job ID for it to be tracked
- [ ] add endpoint to get the status of the flist using the job ID
- [ ] add endpoint to check the health of the server
- [ ] add endpoint to signin (authentication)
- [ ] add endpoint to list flists of the user. (templates are added)
- [ ] add authorization middleware to endpoints except health check
- [ ] support authentication using list of users (username and password per user)
- [ ] add server configurations (`host`, `port`, `store_url`, `flist_dir`, `version,`  `jwt_secret`, `jwt_expire`, `users`)
- [ ] add pagination for listing flists
- [ ] add cors for endpoints
- [ ] add validations for request bodies
- [ ] add validations for configurations
- [ ] try to add auth tokens to the templates

**Comment by rawdaGastan** [comment]
- [ ] clean map of job and status for flists // to be discussed
